name: forecasting-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - mlflow
  - pyyaml
  - pip:
      - mlflow
