name: forecasting-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pandas=1.3.5
  - numpy=1.21.6
  - scikit-learn=1.0.2
  - xgboost=1.5.2
  - pip=23.1.2
  - mlflow=2.3.1
  - psutil=5.9.4
  - pyyaml=6.0
  - pip:
      - pyopenssl==23.2.0